image: java:8-jdk

stages:
  - build

before_script:
  - env
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build distTar
  artifacts:
    paths:
      - build/distributions/*
    expire_in: 1 week
  only:
    - master
