image: java:8-jdk

stages:
  - build
  - package
  - publish

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx512m"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build

tar:
  stage: package
  script:
    - ./gradlew distTar
  only:
    - tags
  artifacts:
    paths:
      - build/distributions/*.tar
    expire_in: 1 week

deb:build:
  stage: package
  image: registry.git.callpipe.com/finn/debian-repo-builder:latest
  before_script:
    - export VERSION=$(git describe --always --tags)
    - echo "Building signald version $VERSION"
  tags:
    - package-signer
  script:
    - dpkg-buildpackage --sign-key=D89FFB45291229A410A1430A659475081F665F29
    - cp -rv ../signald_* .
  only:
    - tags
    - feature/deb-packaging
  artifacts:
    paths:
      - "*.deb"

deb:publish:
  stage: publish
  image: registry.git.callpipe.com/finn/debian-repo-builder:latest
  only:
    - tags
  tags:
    - package-signer
  before_script:
    - mc config host add minio "${MINIO_URL}" "${MINIO_ACCESS_KEY}" "${MINIO_SECRET_KEY}"
    - mkdir public/ && cd public/
    - mc cp -r -q minio/updates.signald.org/ .
  script:
    - release-deb ../ D89FFB45291229A410A1430A659475081F665F29
    - gpg --homedir /opt/signing-keys/.gnupg --export --armor D89FFB45291229A410A1430A659475081F665F29 > apt-signing-key.asc
    - mc cp -r -q . minio/updates.signald.org/
  dependencies:
    - deb:build
