image: gradle:4.10.0

stages:
  - build
  - package

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - gradle build

tar:
  stage: package
  script:
    - gradle distTar
  artifacts:
    paths:
      - build/distributions/*.tar
    expire_in: 1 week

deb:
  stage: package
  before_script:
    - VERSION=$(git describe --always --tags)
  script:
    - gradle deb
  artifacts:
    paths:
      - build/distributions/*.deb
    expire_in: 1 week

rpm:
  stage: package
  script:
    - gradle buildRpm
  artifacts:
    paths:
      - build/distributions/*.rpm
    expire_in: 1 week
