image: java:8-jdk

stages:
  - build
  - package
  - publish

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build

tar:
  stage: package
  script:
    - ./gradlew distTar
  artifacts:
    paths:
      - build/distributions/*.tar
    expire_in: 1 week

deb:build:
  stage: package
  before_script:
    - export VERSION=$(git describe --always --tags)
    - echo "Building signald version $VERSION"
  script:
    - ./gradlew deb
    - mv build/distributions/*.deb .
  only:
    - tags
    - feature/deb-packaging
  artifacts:
    paths:
      - "*.deb"

deb:publish:
  stage: publish
  image: registry.git.callpipe.com/finn/debian-repo-builder:master
  tags:
    - package-signer
  before_script:
    - mc config host add minio "${MINIO_URL}" "${MINIO_ACCESS_KEY}" "${MINIO_SECRET_KEY}"
    - mkdir public/ && cd public/
    - mc cp -r -q minio/updates.signald.org/ .
  script:
    - release-deb ../
    - mc cp -r -q . minio/updates.signald.org/
  dependencies:
    - deb:build
